# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: "openai_rt_client"
  version: 0.1.0

source:
  - path: ../src
  - path: ../LICENSE

build:
  script:
    - magic run mojo package openai_rt_client -o ${PREFIX}/openai_rt_client.mojopkg

requirements:
  run:
    - max >=24.5.0

about:
  homepage: https://github.com/msaelices/mojo-openai-realtime-client
  license: MIT
  license_file: LICENSE
  summary: OpenAI Realtime Client in Mojo
  repository: https://github.com/msaelices/mojo-openai-realtime-client